name = "Cauchy_functional_equation"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Cauchy_functional_equation"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Cauchy_functional_equation"

[dependencies]
mathlib = { git = "https://github.com/leanprover-community/mathlib4" }